const premisseTypes = [
    'ALAMEDA', 'AL',
    'APARTAMENTO', 'AP',
    'AVENIDA', 'AV',
    'BECO', 'BC',
    'BLOCO', 'BL',
    'CAMINHO', 'CAM',
    'ESCADINHA', 'ESCD',
    'ESTAÇÃO', 'EST',
    'ESTRADA', 'ETR',
    'FAZENDA', 'FAZ',
    'FORTALEZA', 'FORT',
    'GALERIA', 'GL',
    'LADEIRA', 'LD',
    'LARGO', 'LGO',
    'PRAÇA', 'PÇA',
    'PARQUE', 'PRQ',
    'PRAIA', 'PR',
    'QUADRA', 'QD',
    'QUILÔMETRO', 'KM',
    'QUINTA', 'QTA',
    'RODOVIA', 'ROD',
    'RUA', 'R',
    'SUPER QUADRA', 'SQD',
    'SUPERQUADRA', 'SQD',
    'TRAVESSA', 'TRV',
    'VIADUTO', 'VD',
    'VILA', 'VL',
]

export { premisseTypes }
